version: '3.8'
services:
  hasii:
    build: .
    container_name: open-heart-music-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./OpenHeartsMusic/cookies:/app/OpenHeartsMusic/cookies
      - ./downloads:/app/downloads
    command: bash start
